# This workflow is inspired from :https://github.com/marketplace/actions/ai-code-review-action

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: cd demo && mvn clean install
      - name: Review pull request
        uses: sshnaidm/gpt-code-review-action
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
